[package]
name = "todo_list"
version = "0.1.0"
edition = "2024"

[[bin]]
name="todo"
path="src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }

